services:
  mongo:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: backend-challenge
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - backend-challenge-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  redis:
    image: redis:8.2-alpine
    container_name: redis
    command: redis-server --requirepass password
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - backend-challenge-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVICE_PORT=8080
      - SERVICE_NAME=backend-challenge-compose
      - SERVICE_BODY_LIMIT=10
      - SERVICE_READ_TIMEOUT=10s
      - SERVICE_WRITE_TIMEOUT=10s
      - SERVICE_MASK_MAP=email:***,password:*******,confirm_password:*******
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=password
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=backend-challenge
      - MONGODB_AUTH_SOURCE=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - REDIS_DB=0
      - JWT_SECRET=83d99c3dc3aedc05235b574a97242e44
      - JWT_ACCESS_TTL=15
      - JWT_REFRESH_TTL=24
    container_name: app
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - backend-challenge-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/livez"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mongo_data:
  mongo_config:
  redis_data:

networks:
  backend-challenge-network:
    driver: bridge
